[project]
name = "sales-manager-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "openai>=2.15.0",
    "openai-agents>=0.6.6",
    "python-dotenv>=1.2.1",
    "sendgrid>=6.12.5",
]
